name = "NestedSamplers"
uuid = "41ceaf6f-1696-4a54-9b49-2e7a9ec3782e"
authors = ["Miles Lucas <mdlucas@hawaii.edu>"]
version = "0.7.1"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AbstractMCMC = "3.0.2"
Clustering = "0.13, 0.14"
Distributions = "0.21,0.22,0.23, 0.24, 0.25"
LogExpFunctions = "0.3"
MCMCChains = "3, 4, 5"
Parameters = "0.12"
ProgressLogging = "0.1"
StatsBase = "0.32, 0.33"
julia = "1.3"
